### ISSUE TITLE
请问具体配置位置。

### ISSUE THREAD

**Issue by rainzee** [ddiu8081/vscode-settings#1]
### Additional context

常年使用VIM，刚转用VSCODE，对VSCODE的体系有点不太理解，在Windows上，有两个位置：
~/.vscode/extensions 这里有 extensions.json 但是没有 settings.json
AppData\Roaming\Code\User 这里有  settings.json 没有 extensions.json

在OSX或者Linux上，同样的：
~/.config/code/User 这里有  settings.json 没有 extensions.json
~/.config/.vscode  这里有  settings.json 没有 extensions.json

**Comment by ddiu8081** [comment]
个人建议用 User 目录下的 `settings.json`，可以 `cmd/ctrl+shift+p` 打开 Command Center，选择 `Open User Settings (JSON)`。

`extensions` 只是一个列表，需要在插件商店搜索对应条目安装，不建议直接复制 `extensions.json` 用。
